# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

users = User.create([{email: 'jan@mail.com', firstname: 'Jan', lastname: 'Kowalski', password: 'NaNaNaNa', password_confirmation: 'NaNaNaNa', admin:true}, {email: 'anna@mail.com', firstname: 'Anna', lastname: 'Kowalska', password: 'NaNaNaNa', password_confirmation: 'NaNaNaNa'},
 {email: 'marek@mail.com', firstname: 'Marek', lastname: 'Kowalski', password: 'NaNaNaNa', password_confirmation: 'NaNaNaNa'}, {email: 'kaja@mail.com', firstname: 'Kaja', lastname: 'Kowalska', password: 'NaNaNaNa', password_confirmation: 'NaNaNaNa'},
 {email: 'adam@mail.com', firstname: 'Adam', lastname: 'Kowalski', password: 'NaNaNaNa', password_confirmation: 'NaNaNaNa'}])

categories = Category.create([{name: 'GoPro Cameras', pictureurl: 'http://cbcdn1.qa1.gp-static.com/media_library/image/113/large_Home_Brandbar_product_actual.jpg'},
  {name:'Nikon Cameras', pictureurl:'http://cdn0.mos.techradar.futurecdn.net///art/cameras/Nikon/D3100/Nikon%20D3100%207-580-100.jpg'},
  {name:'Sony Cameras', pictureurl:'http://www.hitechreview.com/gallery/sony-alpha-a77-slt-a77/slides/sony-slt-a77-digital-camera_04.jpg'},
  {name:'Olympus Cameras', pictureurl:'http://www.wired.com/images_blogs/gadgetlab/2013/09/EM1__front1-660x459.jpg'},
  {name:'Tripods', pictureurl:'http://www.martinbaileyphotography.com/wp-content/uploads/2013/07/MBP_Tripods_20130711_7680.jpg'},
  {name:'Other accessories', pictureurl:'http://g-ecx.images-amazon.com/images/G/02/uk-electronics/product_content/kondor/CAMERA.jpg'}])

category = Category.find_by(name: "GoPro Cameras")
product = Product.create(title: 'GoPro HERO4 black', category_id: category.id,  user_id: 1, price:150, description: "With the ability to capture 4K at 30 fps (4K30), the GoPro HERO4 Black allows you to move beyond HD when recording POV style footage either wearing the camera or mounting it in a number of creative ways. On top of 4K, the camera shoots 2.7K at up to 50 fps, Full HD (1080p) at up to 120 fps for high definition slow motion, WVGA (848 x 480) for upload-friendly files, and more. Plus, with the SuperView mode enabled, the camera maximizes its sensor area to give you an ultra-wide angle of view to enhance the POV feel of footage while encompassing as much of the scene as possible. The HERO4 Black's capabilities don't end with video, though. It can take 12-megapixel stills as individual shots, in intervals for stitching together time-lapse movies, or in momentary bursts of up to 30 photos per second - the latter helping ensure you catch fast action at just the right moment.")
Product.create(title: 'GoPro HERO4 silver', category_id: category.id,  user_id: 1, price:120, description: "With a built-in touch screen LCD for composing shots and accessing the menu, the GoPro HERO4 Silver eliminates the need for an LCD BacPac. It is able to capture Full HD 1080p at up to 60 fps and - for even more detailed shots - capture 2.7K (2704 x 1520) at 30 fps and 4K (3840 x 2160) at 15 fps. There are a number of other frame rates and resolutions as well, including a 100 fps mode ideal for creating slow motion effects that is available in 960p and 720p. But the HERO Silver's capabilities don't stop with video. It can also take 12-megapixel stills, as individual shots, in intervals for stitching together time-lapse movies, or in momentary bursts of up to 30 photos per second - the latter helping ensure you catch fast action at just the right moment.")
Product.create(title: 'GoPro Hero Action', category_id: category.id,  user_id: 1, price:120, description: "Rather than a separate housing, the GoPro HERO Action Camera features a unibody design wherein the camera itself is waterproof to 131' with the Standard Backdoor in place and sealed. It records 1080p30 Full HD video, as well as 720p60 for enhanced motion capture or creating slow-motion effects in post. The HERO also takes 5-megapixel still photos in single shot, burst, and time-lapse. For use on dry land the Skeleton Backdoor is included, featuring cutouts for enhanced audio capture using the built-in microphone.")

Review.create(user_id:1, product_id: product.id, rating: 5, content: "Great Video QualityNo gltiches so far. I Have Jumped the camera about 10 times and riden my motorcycle a bit with it as well. 1440 at 80fps is great for grabbing pictures from video.4k must be great but i don't have anything to watch it on. I have bareley even scratched the surface with all the settings it has. The interface is pretty easy to understand.Battery goes fast when using the bluetooth remote control and filming in high res.I havn't gotten the battery backpack yet, but the single battery generally lasts about an hour.")
Review.create(user_id:1, product_id: product.id, rating: 3, content: "Just OK. We have two Hero3 Black and were looking forward to the 4k at 30fps. Seems like they simply overcranked the Hero3 to output the 30fps. Gets very hot shooting 4K at 30fps. Lots of judder at 23.98 4k as well. Still wish they would make a simple small swivel mount for the GoPro and there are still ergonomic things that I don't love about using this camera. Glad that the WiFi mode was made a menu only setting!")
Review.create(user_id:1, product_id: product.id, rating: 4, content: "The camera is wonderful and works as you'd expect, but you'll need so get some accessory mounts before you can really use it. It comes with minimal mounting hardware, so don't skimp and get what you need.")